-- DSY2201 Semana 6 - Tablas del microservicio ms-citas-medicas
-- Ejecutar conectado como usuario DSY2201_S6


-- Eliminacion previa (por si se re-ejecuta el script)
DROP TABLE cita_medica CASCADE CONSTRAINTS;
DROP TABLE doctor CASCADE CONSTRAINTS;


-- Tabla Doctor
CREATE TABLE doctor (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre          VARCHAR2(100)    NOT NULL,
    especialidad    VARCHAR2(60)     NOT NULL,
    horario_inicio  VARCHAR2(5)      NOT NULL,
    horario_fin     VARCHAR2(5)      NOT NULL,
    disponible      NUMBER(1)        DEFAULT 1 NOT NULL,
    CONSTRAINT pk_doctor PRIMARY KEY (id),
    CONSTRAINT chk_doctor_disponible CHECK (disponible IN (0, 1))
);


-- Tabla CitaMedica (fk a Doctor)
CREATE TABLE cita_medica (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_paciente  VARCHAR2(120)    NOT NULL,
    rut_paciente     VARCHAR2(15)     NOT NULL,
    doctor_id        NUMBER           NOT NULL,
    nombre_doctor    VARCHAR2(100),
    especialidad     VARCHAR2(60),
    fecha            DATE             NOT NULL,
    hora             VARCHAR2(5)      NOT NULL,
    estado           VARCHAR2(15)     NOT NULL,
    motivo           VARCHAR2(255)    NOT NULL,
    CONSTRAINT pk_cita_medica PRIMARY KEY (id),
    CONSTRAINT fk_cita_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (id),
    CONSTRAINT chk_cita_estado CHECK (estado IN ('PROGRAMADA', 'CANCELADA', 'COMPLETADA'))
);


-- Datos iniciales: 5 doctores
INSERT INTO doctor (nombre, especialidad, horario_inicio, horario_fin, disponible)
VALUES ('Dra. Maria Gonzalez', 'Medicina General', '08:00', '16:00', 1);
INSERT INTO doctor (nombre, especialidad, horario_inicio, horario_fin, disponible)
VALUES ('Dr. Carlos Munoz', 'Pediatria', '09:00', '17:00', 1);
INSERT INTO doctor (nombre, especialidad, horario_inicio, horario_fin, disponible)
VALUES ('Dra. Andrea Silva', 'Cardiologia', '08:30', '14:30', 1);
INSERT INTO doctor (nombre, especialidad, horario_inicio, horario_fin, disponible)
VALUES ('Dr. Roberto Fernandez', 'Dermatologia', '10:00', '18:00', 1);
INSERT INTO doctor (nombre, especialidad, horario_inicio, horario_fin, disponible)
VALUES ('Dra. Francisca Lopez', 'Medicina General', '14:00', '20:00', 0);


-- Datos iniciales: 4 citas en distintos estados
INSERT INTO cita_medica (nombre_paciente, rut_paciente, doctor_id, nombre_doctor,
                         especialidad, fecha, hora, estado, motivo)
VALUES ('Juan Perez Soto', '12.345.678-9', 1, 'Dra. Maria Gonzalez',
        'Medicina General', DATE '2026-05-15', '09:00', 'PROGRAMADA',
        'Control general anual');

INSERT INTO cita_medica (nombre_paciente, rut_paciente, doctor_id, nombre_doctor,
                         especialidad, fecha, hora, estado, motivo)
VALUES ('Ana Torres Vega', '15.678.901-2', 2, 'Dr. Carlos Munoz',
        'Pediatria', DATE '2026-05-16', '10:00', 'PROGRAMADA',
        'Vacunacion infantil');

INSERT INTO cita_medica (nombre_paciente, rut_paciente, doctor_id, nombre_doctor,
                         especialidad, fecha, hora, estado, motivo)
VALUES ('Pedro Rojas Diaz', '10.234.567-8', 3, 'Dra. Andrea Silva',
        'Cardiologia', DATE '2026-04-10', '09:00', 'COMPLETADA',
        'Examen cardiologico de rutina');

INSERT INTO cita_medica (nombre_paciente, rut_paciente, doctor_id, nombre_doctor,
                         especialidad, fecha, hora, estado, motivo)
VALUES ('Maria Fernanda Contreras', '18.901.234-5', 4, 'Dr. Roberto Fernandez',
        'Dermatologia', DATE '2026-04-12', '11:00', 'CANCELADA',
        'Revision de lunares');

COMMIT;


-- Verificacion
SELECT 'DOCTOR' AS tabla, COUNT(*) AS total FROM doctor
UNION ALL
SELECT 'CITA_MEDICA', COUNT(*) FROM cita_medica;
