-- DSY2201 Semana 6 - Tablas del microservicio ms-ordenes-mascotas
-- Ejecutar conectado como usuario DSY2201_S6


-- Eliminacion previa (por si se re-ejecuta el script)
DROP TABLE item_orden CASCADE CONSTRAINTS;
DROP TABLE orden_compra CASCADE CONSTRAINTS;
DROP TABLE producto CASCADE CONSTRAINTS;


-- Tabla Producto (catalogo)
CREATE TABLE producto (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre       VARCHAR2(120)    NOT NULL,
    descripcion  VARCHAR2(500),
    precio       NUMBER(10, 2)    NOT NULL,
    categoria    VARCHAR2(50)     NOT NULL,
    stock        NUMBER(6)        DEFAULT 0 NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id),
    CONSTRAINT chk_producto_precio CHECK (precio >= 0),
    CONSTRAINT chk_producto_stock CHECK (stock >= 0)
);


-- Tabla OrdenCompra
CREATE TABLE orden_compra (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    nombre_cliente  VARCHAR2(120)    NOT NULL,
    email_cliente   VARCHAR2(120)    NOT NULL,
    fecha_creacion  DATE             DEFAULT SYSDATE NOT NULL,
    total           NUMBER(12, 2)    DEFAULT 0 NOT NULL,
    estado          VARCHAR2(15)     NOT NULL,
    CONSTRAINT pk_orden_compra PRIMARY KEY (id),
    CONSTRAINT chk_orden_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA'))
);


-- Tabla ItemOrden (FK a orden y a producto). Cascade delete al eliminar la orden.
CREATE TABLE item_orden (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    orden_id          NUMBER           NOT NULL,
    producto_id       NUMBER           NOT NULL,
    nombre_producto   VARCHAR2(120),
    cantidad          NUMBER(5)        NOT NULL,
    precio_unitario   NUMBER(10, 2)    NOT NULL,
    subtotal          NUMBER(12, 2)    NOT NULL,
    CONSTRAINT pk_item_orden PRIMARY KEY (id),
    CONSTRAINT fk_item_orden FOREIGN KEY (orden_id)
        REFERENCES orden_compra (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_producto FOREIGN KEY (producto_id)
        REFERENCES producto (id),
    CONSTRAINT chk_item_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_item_precio CHECK (precio_unitario >= 0)
);


-- Datos iniciales: 8 productos
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Alimento Premium para Perros', 'Alimento seco premium, saco de 15 kg.', 32990, 'Alimentacion', 50);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Juguete Mordedor', 'Juguete de caucho resistente para perros.', 8990, 'Juguetes', 120);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Collar Antipulgas', 'Collar antipulgas, proteccion por 8 meses.', 15990, 'Medicamentos', 75);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Shampoo para Gatos', 'Shampoo hipoalergenico, 500 ml.', 6990, 'Higiene', 90);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Cama para Mascotas', 'Cama acolchada lavable tamano mediano.', 24990, 'Accesorios', 35);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Arena para Gatos', 'Arena aglomerante premium, bolsa de 10 kg.', 11990, 'Higiene', 60);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Snacks Dentales', 'Snacks dentales para perros.', 5990, 'Alimentacion', 200);
INSERT INTO producto (nombre, descripcion, precio, categoria, stock)
VALUES ('Transportador de Mascotas', 'Transportador rigido aprobado para vuelos.', 45990, 'Accesorios', 20);


-- Datos iniciales: 3 ordenes (una por estado)
INSERT INTO orden_compra (nombre_cliente, email_cliente, fecha_creacion, total, estado)
VALUES ('Maria Gonzalez', 'maria.gonzalez@mail.cl', DATE '2026-04-05', 83950, 'PENDIENTE');
INSERT INTO orden_compra (nombre_cliente, email_cliente, fecha_creacion, total, estado)
VALUES ('Carlos Munoz', 'carlos.munoz@mail.cl', DATE '2026-04-02', 29970, 'CONFIRMADA');
INSERT INTO orden_compra (nombre_cliente, email_cliente, fecha_creacion, total, estado)
VALUES ('Andrea Lopez', 'andrea.lopez@mail.cl', DATE '2026-03-28', 70980, 'CANCELADA');


-- Items de las ordenes (2 por orden)
INSERT INTO item_orden (orden_id, producto_id, nombre_producto, cantidad, precio_unitario, subtotal)
VALUES (1, 1, 'Alimento Premium para Perros', 2, 32990, 65980);
INSERT INTO item_orden (orden_id, producto_id, nombre_producto, cantidad, precio_unitario, subtotal)
VALUES (1, 7, 'Snacks Dentales', 3, 5990, 17970);

INSERT INTO item_orden (orden_id, producto_id, nombre_producto, cantidad, precio_unitario, subtotal)
VALUES (2, 3, 'Collar Antipulgas', 1, 15990, 15990);
INSERT INTO item_orden (orden_id, producto_id, nombre_producto, cantidad, precio_unitario, subtotal)
VALUES (2, 4, 'Shampoo para Gatos', 2, 6990, 13980);

INSERT INTO item_orden (orden_id, producto_id, nombre_producto, cantidad, precio_unitario, subtotal)
VALUES (3, 5, 'Cama para Mascotas', 1, 24990, 24990);
INSERT INTO item_orden (orden_id, producto_id, nombre_producto, cantidad, precio_unitario, subtotal)
VALUES (3, 8, 'Transportador de Mascotas', 1, 45990, 45990);

COMMIT;


-- Verificacion
SELECT 'PRODUCTO' AS tabla, COUNT(*) AS total FROM producto
UNION ALL
SELECT 'ORDEN_COMPRA', COUNT(*) FROM orden_compra
UNION ALL
SELECT 'ITEM_ORDEN', COUNT(*) FROM item_orden;
